apiVersion: v1
kind: Service
metadata:
  name: {{ include "inbox-server-distributed.fullname" . }}-cassandra
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: cassandra
    {{- include "inbox-server-distributed.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "9042"
      port: 9042
      targetPort: 9042
  selector:
    app.kubernetes.io/component: cassandra
    {{- include "inbox-server-distributed.selectorLabels" . | nindent 4 }}
