properties:
  adminIngress:
    properties:
      annotations:
        additionalProperties:
          type: string
        type: object
      className:
        type: string
      enabled:
        type: boolean
      tls:
        properties:
          secretName:
            type: string
        required:
        - secretName
        type: object
    required:
    - annotations
    - className
    - enabled
    - tls
    type: object
  cassandra:
    properties:
      image:
        properties:
          pullPolicy:
            type: string
          repository:
            type: string
          tag:
            type: string
        required:
        - pullPolicy
        - repository
        - tag
        type: object
      livenessProbe:
        description: Probe describes a health check to be performed against a container
          to determine whether it is alive or ready to receive traffic.
        properties:
          exec:
            description: Exec specifies the action to take.
            properties:
              command:
                description: Command is the command line to execute inside the container,
                  the working directory for the command  is root ('/') in the container's
                  filesystem. The command is simply exec'd, it is not run inside a
                  shell, so traditional shell instructions ('|', etc) won't work.
                  To use a shell, you need to explicitly call out to that shell. Exit
                  status of 0 is treated as live/healthy and non-zero is unhealthy.
                items:
                  type: string
                type: array
                x-kubernetes-list-type: atomic
            type: object
          failureThreshold:
            description: Minimum consecutive failures for the probe to be considered
              failed after having succeeded. Defaults to 3. Minimum value is 1.
            format: int32
            type: integer
          grpc:
            description: GRPC specifies an action involving a GRPC port.
            properties:
              port:
                description: Port number of the gRPC service. Number must be in the
                  range 1 to 65535.
                format: int32
                type: integer
              service:
                description: "Service is the name of the service to place in the gRPC\
                  \ HealthCheckRequest (see https://github.com/grpc/grpc/blob/master/doc/health-checking.md).\
                  \ \n If this is not specified, the default behavior is defined by\
                  \ gRPC."
                type: string
            required:
            - port
            type: object
          httpGet:
            description: HTTPGet specifies the http request to perform.
            properties:
              host:
                description: Host name to connect to, defaults to the pod IP. You
                  probably want to set "Host" in httpHeaders instead.
                type: string
              httpHeaders:
                description: Custom headers to set in the request. HTTP allows repeated
                  headers.
                items:
                  description: HTTPHeader describes a custom header to be used in
                    HTTP probes
                  properties:
                    name:
                      description: The header field name. This will be canonicalized
                        upon output, so case-variant names will be understood as the
                        same header.
                      type: string
                    value:
                      description: The header field value
                      type: string
                  required:
                  - name
                  - value
                  type: object
                type: array
                x-kubernetes-list-type: atomic
              path:
                description: Path to access on the HTTP server.
                type: string
              port:
                anyOf:
                - type: integer
                - type: string
                description: Name or number of the port to access on the container.
                  Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
                x-kubernetes-int-or-string: true
              scheme:
                description: Scheme to use for connecting to the host. Defaults to
                  HTTP.
                type: string
            required:
            - port
            type: object
          initialDelaySeconds:
            description: 'Number of seconds after the container has started before
              liveness probes are initiated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes'
            format: int32
            type: integer
          periodSeconds:
            description: How often (in seconds) to perform the probe. Default to 10
              seconds. Minimum value is 1.
            format: int32
            type: integer
          successThreshold:
            description: Minimum consecutive successes for the probe to be considered
              successful after having failed. Defaults to 1. Must be 1 for liveness
              and startup. Minimum value is 1.
            format: int32
            type: integer
          tcpSocket:
            description: TCPSocket specifies an action involving a TCP port.
            properties:
              host:
                description: 'Optional: Host name to connect to, defaults to the pod
                  IP.'
                type: string
              port:
                anyOf:
                - type: integer
                - type: string
                description: Number or name of the port to access on the container.
                  Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
                x-kubernetes-int-or-string: true
            required:
            - port
            type: object
          terminationGracePeriodSeconds:
            description: Optional duration in seconds the pod needs to terminate gracefully
              upon probe failure. The grace period is the duration in seconds after
              the processes running in the pod are sent a termination signal and the
              time when the processes are forcibly halted with a kill signal. Set
              this value longer than the expected cleanup time for your process. If
              this value is nil, the pod's terminationGracePeriodSeconds will be used.
              Otherwise, this value overrides the value provided by the pod spec.
              Value must be non-negative integer. The value zero indicates stop immediately
              via the kill signal (no opportunity to shut down). This is a beta field
              and requires enabling ProbeTerminationGracePeriod feature gate. Minimum
              value is 1. spec.terminationGracePeriodSeconds is used if unset.
            format: int64
            type: integer
          timeoutSeconds:
            description: 'Number of seconds after which the probe times out. Defaults
              to 1 second. Minimum value is 1. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes'
            format: int32
            type: integer
        type: object
    required:
    - image
    - livenessProbe
    type: object
  dns:
    properties:
      domain:
        type: string
      emailDomain:
        type: string
      targetIPs:
        items:
          type: string
        type: array
    required:
    - domain
    - emailDomain
    - targetIPs
    type: object
  fullnameOverride:
    type: string
  ingress:
    properties:
      annotations:
        additionalProperties:
          type: string
        type: object
      className:
        type: string
      enabled:
        type: boolean
      tls:
        properties:
          secretName:
            type: string
        required:
        - secretName
        type: object
    required:
    - annotations
    - className
    - enabled
    - tls
    type: object
  james:
    properties:
      env:
        properties:
          cassandraReplicationFactor:
            type: integer
          glowroot:
            properties:
              enabled:
                type: boolean
            required:
            - enabled
            type: object
          jamesCassandraCacheKeyspace:
            type: string
          jamesCassandraKeyspace:
            type: string
          jamesDkimSignDomain:
            type: string
          jamesDkimSignSmtp:
            type: string
          jamesEsClusterName:
            type: string
          jamesEsHostNameVerifier:
            type: string
          jamesEsHostScheme:
            type: string
          jamesEsMailboxIndex:
            type: string
          jamesEsMailboxReadAlias:
            type: string
          jamesEsMailboxWriteAlias:
            type: string
          jamesEsNbReplica:
            type: integer
          jamesEsNbShards:
            type: integer
          jamesEsSslValidationStrategy:
            type: string
          jamesHELOMessage:
            type: string
          jamesKeyStorePassword:
            type: string
          jamesMessageSize:
            type: string
          jamesRabbitHost:
            type: string
          jamesResources:
            description: ResourceRequirements describes the compute resource requirements.
            properties:
              claims:
                description: "Claims lists the names of resources, defined in spec.resourceClaims,\
                  \ that are used by this container. \n This is an alpha field and\
                  \ requires enabling the DynamicResourceAllocation feature gate.\
                  \ \n This field is immutable. It can only be set for containers."
                items:
                  description: ResourceClaim references one entry in PodSpec.ResourceClaims.
                  properties:
                    name:
                      description: Name must match the name of one entry in pod.spec.resourceClaims
                        of the Pod where this field is used. It makes that resource
                        available inside a container.
                      type: string
                  required:
                  - name
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - name
                x-kubernetes-list-type: map
              limits:
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                description: 'Limits describes the maximum amount of compute resources
                  allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                type: object
              requests:
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                description: 'Requests describes the minimum amount of compute resources
                  required. If Requests is omitted for a container, it defaults to
                  Limits if that is explicitly specified, otherwise to an implementation-defined
                  value. Requests cannot exceed Limits. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                type: object
            type: object
          jvmOpts:
            type: string
        required:
        - cassandraReplicationFactor
        - glowroot
        - jamesCassandraCacheKeyspace
        - jamesCassandraKeyspace
        - jamesDkimSignDomain
        - jamesDkimSignSmtp
        - jamesEsClusterName
        - jamesEsHostNameVerifier
        - jamesEsHostScheme
        - jamesEsMailboxIndex
        - jamesEsMailboxReadAlias
        - jamesEsMailboxWriteAlias
        - jamesEsNbReplica
        - jamesEsNbShards
        - jamesEsSslValidationStrategy
        - jamesHELOMessage
        - jamesKeyStorePassword
        - jamesMessageSize
        - jamesRabbitHost
        - jamesResources
        - jvmOpts
        type: object
      image:
        type: string
      replicaImapSmtpInstanceCount:
        type: integer
      replicaJmapInstanceCount:
        type: integer
      secret:
        properties:
          adminJWTPublicKey:
            type: string
          dkimPrivateKey:
            type: string
          jwtPrivateKey:
            type: string
          jwtPublicKey:
            type: string
        required:
        - adminJWTPublicKey
        - dkimPrivateKey
        - jwtPrivateKey
        - jwtPublicKey
        type: object
      tls:
        properties:
          secretName:
            type: string
        required:
        - secretName
        type: object
    required:
    - env
    - image
    - replicaImapSmtpInstanceCount
    - replicaJmapInstanceCount
    - tls
    type: object
  nameOverride:
    type: string
  opensearch:
    properties:
      enabled:
        type: boolean
      image:
        properties:
          pullPolicy:
            type: string
          repository:
            type: string
          tag:
            type: string
        required:
        - pullPolicy
        - repository
        - tag
        type: object
    required:
    - enabled
    - image
    type: object
  rabbitmq:
    properties:
      image:
        properties:
          pullPolicy:
            type: string
          repository:
            type: string
          tag:
            type: string
        required:
        - pullPolicy
        - repository
        - tag
        type: object
    required:
    - image
    type: object
  s3:
    properties:
      enabled:
        type: boolean
      image:
        properties:
          pullPolicy:
            type: string
          repository:
            type: string
          tag:
            type: string
        required:
        - pullPolicy
        - repository
        - tag
        type: object
    required:
    - enabled
    - image
    type: object
  service:
    properties:
      type:
        type: string
    required:
    - type
    type: object
  serviceMonitor:
    properties:
      additionalLabels:
        additionalProperties:
          type: string
        type: object
      enabled:
        type: boolean
      interval:
        type: string
    required:
    - additionalLabels
    - enabled
    - interval
    type: object
  tika:
    properties:
      enabled:
        type: boolean
      image:
        properties:
          pullPolicy:
            type: string
          repository:
            type: string
          tag:
            type: string
        required:
        - pullPolicy
        - repository
        - tag
        type: object
    required:
    - enabled
    - image
    type: object
required:
- adminIngress
- cassandra
- dns
- fullnameOverride
- ingress
- james
- nameOverride
- opensearch
- rabbitmq
- s3
- service
- serviceMonitor
- tika
type: object
