---
apiVersion: v2
description: Inbox Server by AppsCode
name: inbox-server
version: v2025.2.28
appVersion: v0.0.1
home: https://github.com/ops-center
icon: https://cdn.appscode.com/images/products/searchlight/searchlight-512x512.png
sources: [https://github.com/ops-center]
maintainers:
  - name: appscode
    email: support@appscode.com
dependencies:
  - name: postgresql
    version: 16.4.14
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
