properties:
  adminIngress:
    properties:
      annotations:
        additionalProperties:
          type: string
        type: object
      className:
        type: string
      enabled:
        type: boolean
      tls:
        properties:
          secretName:
            type: string
        required:
        - secretName
        type: object
    required:
    - annotations
    - className
    - enabled
    - tls
    type: object
  dns:
    properties:
      domain:
        type: string
      emailDomain:
        type: string
      targetIPs:
        items:
          type: string
        type: array
    required:
    - domain
    - emailDomain
    - targetIPs
    type: object
  fullnameOverride:
    type: string
  ingress:
    properties:
      annotations:
        additionalProperties:
          type: string
        type: object
      className:
        type: string
      enabled:
        type: boolean
      tls:
        properties:
          secretName:
            type: string
        required:
        - secretName
        type: object
    required:
    - annotations
    - className
    - enabled
    - tls
    type: object
  james:
    properties:
      env:
        properties:
          glowroot:
            properties:
              enabled:
                type: boolean
            required:
            - enabled
            type: object
          jamesDkimSignDomain:
            type: string
          jamesDkimSignSmtp:
            type: string
          jamesHELOMessage:
            type: string
          jamesKeyStorePassword:
            type: string
          jamesMessageSize:
            type: string
          jamesResources:
            description: ResourceRequirements describes the compute resource requirements.
            properties:
              claims:
                description: "Claims lists the names of resources, defined in spec.resourceClaims,\
                  \ that are used by this container. \n This is an alpha field and\
                  \ requires enabling the DynamicResourceAllocation feature gate.\
                  \ \n This field is immutable. It can only be set for containers."
                items:
                  description: ResourceClaim references one entry in PodSpec.ResourceClaims.
                  properties:
                    name:
                      description: Name must match the name of one entry in pod.spec.resourceClaims
                        of the Pod where this field is used. It makes that resource
                        available inside a container.
                      type: string
                  required:
                  - name
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - name
                x-kubernetes-list-type: map
              limits:
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                description: 'Limits describes the maximum amount of compute resources
                  allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                type: object
              requests:
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                description: 'Requests describes the minimum amount of compute resources
                  required. If Requests is omitted for a container, it defaults to
                  Limits if that is explicitly specified, otherwise to an implementation-defined
                  value. Requests cannot exceed Limits. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                type: object
            type: object
          jvmOpts:
            type: string
        required:
        - glowroot
        - jamesDkimSignDomain
        - jamesDkimSignSmtp
        - jamesHELOMessage
        - jamesKeyStorePassword
        - jamesMessageSize
        - jamesResources
        - jvmOpts
        type: object
      image:
        type: string
      replicaImapSmtpInstanceCount:
        type: integer
      replicaJmapInstanceCount:
        type: integer
      secret:
        properties:
          adminJWTPublicKey:
            type: string
          dkimPrivateKey:
            type: string
          jwtPrivateKey:
            type: string
          jwtPublicKey:
            type: string
        required:
        - adminJWTPublicKey
        - dkimPrivateKey
        - jwtPrivateKey
        - jwtPublicKey
        type: object
      tls:
        properties:
          secretName:
            type: string
        required:
        - secretName
        type: object
    required:
    - env
    - image
    - replicaImapSmtpInstanceCount
    - replicaJmapInstanceCount
    - tls
    type: object
  nameOverride:
    type: string
  postgresql:
    properties:
      auth:
        properties:
          database:
            type: string
          password:
            type: string
          secretName:
            type: string
          username:
            type: string
        required:
        - database
        - password
        - secretName
        - username
        type: object
      enabled:
        type: boolean
      external:
        properties:
          addr:
            type: string
        required:
        - addr
        type: object
    required:
    - enabled
    type: object
  serviceMonitor:
    properties:
      additionalLabels:
        additionalProperties:
          type: string
        type: object
      enabled:
        type: boolean
      interval:
        type: string
    required:
    - additionalLabels
    - enabled
    - interval
    type: object
required:
- adminIngress
- dns
- fullnameOverride
- ingress
- james
- nameOverride
- postgresql
- serviceMonitor
type: object
