apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inbox-agent.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inbox-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  jmapSessionEndpoint: {{ .Values.inboxServer.jmapSessionEndpoint }}
  webadminEndpoint: {{ .Values.inboxServer.webadminEndpoint }}
  token: {{.Values.inboxServer.token}}
