apiVersion: v1
kind: Service
metadata:
  name: {{ include "inbox-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: operator
    {{- include "inbox-agent.labels" . | nindent 4 }}
spec:
  ports:
  - name: api
    port: 443
    targetPort: 8443
  selector:
    app.kubernetes.io/component: operator
    {{- include "inbox-agent.selectorLabels" . | nindent 4 }}
