{{- $major := default "0" .Capabilities.KubeVersion.Major | trimSuffix "+" | int64 }}
{{- $minor := default "0" .Capabilities.KubeVersion.Minor | trimSuffix "+" | int64 }}
{{- $criticalAddon := and .Values.criticalAddon (or (eq .Release.Namespace "kube-system") (and (ge $major 1) (ge $minor 17))) -}}

{{- $nodeSelector := .Values.nodeSelector }}
{{- if .Values.global }}
  {{ $nodeSelector = default .Values.nodeSelector .Values.global.nodeSelector }}
{{- end }}

{{- $tolerations := .Values.tolerations }}
{{- if .Values.global }}
  {{ $tolerations = default .Values.tolerations .Values.global.tolerations }}
{{- end }}

{{- $affinity := .Values.affinity }}
{{- if .Values.global }}
  {{ $affinity = default .Values.affinity .Values.global.affinity }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inbox-agent.fullname" . }}-webhook-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: webhook-server
    {{- include "inbox-agent.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: webhook-server
      {{- include "inbox-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: webhook-server
        {{- include "inbox-agent.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/apiregistration.yaml: {{ include (print $.Template.BasePath "/webhook/cert.yaml") . | sha256sum }}
      {{- if $criticalAddon }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "appscode.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "inbox-agent.serviceAccountName" . }}
      containers:
      - name: webhook-server
        image: "{{ include "operator.registry" . }}/{{ .Values.operator.repository }}:{{ .Values.operator.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          {{- toYaml .Values.operator.securityContext | nindent 10 }}
        args:
        - webhook
        - --webhook-name={{ include "inbox-agent.fullname" . }}
      {{- if .Values.inboxServer.jmapEndpoint }}
        - --jmapEndpoint={{ .Values.inboxServer.jmapEndpoint }}
      {{- end }}
      {{- if .Values.inboxServer.webadminEndpoint }}
        - --webadminEndpoint={{ .Values.inboxServer.webadminEndpoint }}
      {{- end }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INBOX_SERVER_WEBADMIN_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: {{ include "inbox-agent.fullname" . }}-config
              key: webadminEndpoint
        - name: INBOX_SERVER_JMAP_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: {{ include "inbox-agent.fullname" . }}-config
              key: jmapEndpoint
        - name: INBOX_SERVER_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "inbox-agent.fullname" . }}-config
              key: token
        ports:
        - name: webhook-server
          containerPort: 9443
          protocol: TCP
      {{- if .Values.apiserver.healthcheck.enabled }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
      {{- end }}
        resources:
          {{- toYaml .Values.operator.resources | nindent 10 }}
        volumeMounts:
        - name: serving-cert
          mountPath: /var/serving-cert
          readOnly: true
      - name: kube-rbac-proxy
        image: "{{ include "rbacproxy.registry" . }}/{{ .Values.rbacproxy.repository }}:{{ .Values.rbacproxy.tag }}"
        securityContext:
          {{- toYaml .Values.rbacproxy.securityContext | nindent 10 }}
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          {{- toYaml .Values.rbacproxy.resources | nindent 10 }}
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ include "inbox-agent.fullname" . }}-webhook-cert
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if or $tolerations $criticalAddon }}
      tolerations:
      {{- with $tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $criticalAddon }}
        - key: CriticalAddonsOnly
          operator: Exists
      {{- end -}}
    {{- end -}}
    {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if $criticalAddon }}
      priorityClassName: system-cluster-critical
    {{- end -}}
