{{- if .Values.apiserver.enableMutatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "inbox-agent.fullname" . }}
  labels:
    {{- include "inbox-agent.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "inbox-agent.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-apps-k8s-appscode-com-v1-inbox-agent
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: inbox-agents.monitoring.appscode.com
    rules:
      - apiGroups:
          - monitoring.appscode.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inbox-agents
    sideEffects: None
{{ end }}
