apiVersion: v1
data:
  jwt_publickey: "{{ .Values.james.secret.jwtPublicKey | b64enc }}"
  jwt_privatekey: "{{ .Values.james.secret.jwtPrivateKey | b64enc }}"
  admin_jwt_publickey: "{{ .Values.james.secret.adminJWTPublicKey | b64enc }}"
kind: Secret
type: Opaque
metadata:
  name: {{ include "inbox-server.fullname" . }}-jwt-key
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  dkim.key: "{{ .Values.james.secret.dkimPrivateKey | b64enc }}"
kind: Secret
type: Opaque
metadata:
  name: dkim-private-key
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  username: "{{ .Values.cassandra.secret.username | b64enc }}"
  password: "{{ .Values.cassandra.secret.password | b64enc }}"
kind: Secret
type: Opaque
metadata:
  name: {{ include "inbox-server.fullname" . }}-cassandra-auth
  namespace: {{ .Release.Namespace }}
---
{{- if and (.Values.opensearch.secret.username) (.Values.opensearch.secret.password) }}
apiVersion: v1
data:
  username: "{{ .Values.opensearch.secret.username | b64enc }}"
  password: "{{ .Values.opensearch.secret.password | b64enc }}"
kind: Secret
type: Opaque
metadata:
  name: {{ include "inbox-server.fullname" . }}-openssearch-auth
  namespace: {{ .Release.Namespace }}
{{- end }}
---
apiVersion: v1
data:
  OS_S3_ENDPOINT: {{ .Values.s3.endpoint | b64enc }}
  OS_S3_REGION: {{ .Values.s3.region | b64enc }}
  OS_S3_ACCESSKEYID: {{ .Values.s3.accessKeyId | b64enc }}
  OS_S3_SECRETKEY: {{ .Values.s3.secretKey | b64enc }}
kind: Secret
type: Opaque
metadata:
  name: {{ include "inbox-server.fullname" . }}-s3-auth
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  username: "{{ .Values.rabbitmq.secret.username | b64enc }}"
  password: "{{ .Values.rabbitmq.secret.password | b64enc }}"
kind: Secret
type: Opaque
metadata:
  name: {{ include "inbox-server.fullname" . }}-rabbitmq-auth
  namespace: {{ .Release.Namespace }}
