{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "inbox-server.fullname" . }}-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      {{- include "inbox-server.labels" . | nindent 6 }}
      app.kubernetes.io/part-of: james
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: web
      path: /metrics
{{- end }}
