# Default values for inbox-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overrides name template
nameOverride: ""
# Overrides fullname template
fullnameOverride: ""
# Number of stash operator replicas to create (only 1 is supported)
replicaCount: 1

# Docker registry fqdn used to pull Stash related images.
# Set this to use docker registry hosted at ${registryFQDN}/${registry}/${image}
registryFQDN: ghcr.io
operator:
  # Docker registry used to pull operator image
  registry: appscode
  # Name of operator container image
  repository: inbox-agent
  # Operator container image tag
  tag: ""
  # Compute Resources required by the operator container
  resources: # +doc-gen:break
    requests:
      cpu: "100m"
  # Security options this container should run with
  securityContext: # +doc-gen:break
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault

rbacproxy:
  # Docker registry used to pull operator image
  registry: appscode
  # Name of operator container image
  repository: kube-rbac-proxy
  # Operator container image tag
  tag: v0.11.0
  # Compute Resources required by the operator container
  resources: # +doc-gen:break
    requests:
      cpu: "100m"
  # Security options this container should run with
  securityContext: # +doc-gen:break
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault

# Specify an array of imagePullSecrets.
# Secrets must be manually created in the namespace.
#
# Example:
# helm template charts/stash \
#   --set imagePullSecrets[0].name=sec0 \
#   --set imagePullSecrets[1].name=sec1
imagePullSecrets: []
# Container image pull policy
imagePullPolicy: IfNotPresent
# If true, installs Stash operator as critical addon
criticalAddon: false
# Log level for operator
logLevel: 3
# Annotations applied to operator deployment
annotations: {}
# Annotations passed to operator pod(s).
podAnnotations: {}
# Labels passed to operator pod(s)
podLabels: {}
# Node labels for pod assignment
nodeSelector: # +doc-gen:break
  kubernetes.io/os: linux
# Tolerations for pod assignment
tolerations: []
# Affinity rules for pod assignment
affinity: {}
# Security options the operator pod should run with.
podSecurityContext: # +doc-gen:break
  fsGroup: 65535
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
apiserver:
  # The minimum priority the webhook api group should have at least. Please see
  # https://github.com/kubernetes/kube-aggregator/blob/release-1.9/pkg/apis/apiregistration/v1beta1/types.go#L58-L64
  # for more information on proper values of this field.
  groupPriorityMinimum: 10000
  # The ordering of the webhook api inside of the group. Please see
  # https://github.com/kubernetes/kube-aggregator/blob/release-1.9/pkg/apis/apiregistration/v1beta1/types.go#L66-L70
  # for more information on proper values of this field
  versionPriority: 15
  # If true, mutating webhook is configured for Kubernetes workloads
  enableMutatingWebhook: false
  # If true, validating webhook is configured for Stash CRDss
  enableValidatingWebhook: false
  # CA certificate used by the Kubernetes api server. This field is automatically assigned by the operator.
  ca: not-ca-cert
  # If true, bypasses checks that validating webhook is actually enabled in the Kubernetes cluster.
  bypassValidatingWebhookXray: false
  # If true, uses kube-apiserver FQDN for AKS cluster to workaround https://github.com/Azure/AKS/issues/522 (default true)
  useKubeapiserverFqdnForAks: true
  healthcheck:
    # If true, enables the readiness and liveliness probes for the operator pod.
    enabled: false
  servingCerts:
    # If true, generates on install/upgrade the certs that allow the kube-apiserver (and potentially ServiceMonitor)
    # to authenticate operators pods. Otherwise specify certs in `apiserver.servingCerts.{caCrt, serverCrt, serverKey}`.
    generate: true
    # CA certficate used by serving certificate of webhook server.
    caCrt: ""
    # Serving certficate used by webhook server.
    serverCrt: ""
    # Private key for the serving certificate used by webhook server.
    serverKey: ""

monitoring:
  # Name of monitoring agent (either "prometheus.io/operator" or "prometheus.io/builtin")
  agent: "none"
  serviceMonitor:
    # Specify the labels for ServiceMonitor.
    # Prometheus crd will select ServiceMonitor using these labels.
    # Only usable when monitoring agent is `prometheus.io/operator`.
    labels: {}

inboxServer:
  endpoint: http://james.appscode.ninja/jmap/session
  token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0dXNlcjEub3JnQG15ZG9tYWluIiwiaWF0IjoxNjE2MjM5MDIyLCJleHAiOjE5NDYyMzkwMjJ9.ZQuDcCFyccpSvAtp0M88TeATePlx4Gvs97_asg75cn46Xkoe-ENVYM-N_ZeWs8G7joxCQS2R2BOQ1LPXY7rFYubEA1Ne8xMMJvS6LW8NktdYrSUZm3J7oyeC6K42cHqYlspK2RaiUl-XKaxy0J38p9MhIKvzOETTEpaABFNp5MplNqkVoAnYnOnF8Ez7AfoCnieBuxmR_qmZpRNdl6XXpoyoihv0azY2RxAyk6uRrnNbzirICuthnkFdllPrbffTcRk9NXkV9PyGlmdAVczxeUADIpd2WMWyoB3yFVe4s1dl9UQp7QsJqpBUUuY3LhE295PwzGDq5WKMWzdII55N2BnVe9LS33GXMU9oGgWqpBmxrTzSwc-jiewhorcc32keXkrxhtxL1uNXuYzg2lqFv7he7aTKWowkI2MJVXLhUN-xpIuaKgAgWY99VBYcf5gfhLfwSYVVZUKIQmYI7Jh0bWNoTHyXoHj0wyFnzNe3SsPECip2WohIDD7_CNLydGDvFmdVp7_aIDAHpiA2BrLysm2Go9GHy-ESdVsma6aG95EeICp1ngLSFHx4IOQ3Oisr4t4DStv7INQQQDkuI6hjhVctbt75rcTa-541a237N3RuBKhOPhEbf3eipUD2t-x28Wi_EHDQpFb0D0nZjvI8Q0AoNm0K9rDzVKvUiyNSIr8
