apiVersion: v1
kind: Service
metadata:
  name: {{ include "inbox-server-distributed.fullname" . }}-rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: rabbitmq
    {{- include "inbox-server-distributed.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    app.kubernetes.io/component: rabbitmq
    {{- include "inbox-server-distributed.selectorLabels" . | nindent 4 }}
