{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "inbox-server-lite.fullname" . }}-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app.kubernetes.io/part-of: james
      {{- include "inbox-server-lite.labels" . | nindent 8 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: web
    path: /metrics
{{- end }}