---
apiVersion: v2
name: appscode-otel-stack
description: AppsCode OpenTelemetry Stack
type: application
version: v2025.2.28
appVersion: v2025.2.28
home: https://github.com/ops-center
icon: https://cdn.appscode.com/images/products/searchlight/searchlight-512x512.png
sources: [https://github.com/ops-center]
maintainers:
  - name: appscode
    email: support@appscode.com
dependencies:
  - name: kube-prometheus-stack
    repository: oci://ghcr.io/appscode-charts
    condition: kube-prometheus-stack.enabled
    version: 71.2.0
  - name: opentelemetry-kube-stack
    repository: oci://ghcr.io/appscode-charts
    condition: opentelemetry-kube-stack.enabled
    version: 0.3.13
